apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-secrets
  namespace: prod
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "2df9028f-bf9e-438f-9cde-1f1764e4ddfc" # Client ID of the Workload Identity
    keyvaultName: "incident-tracker-kv"
    objects:  |
      array:
        - |
          objectName: postgresuser
          objectType: secret
        - |
          objectName: postgrespassword
          objectType: secret
        - |
          objectName: azuretenantid
          objectType: secret
        - |
          objectName: apikey
          objectType: secret
        - |
          objectName: openapiendpoint
          objectType: secret
        - |
          objectName: storage
          objectType: secret
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - objectName: postgresuser
          key: POSTGRES_USER
        - objectName: postgrespassword
          key: POSTGRES_PASSWORD
        - objectName: azuretenantid
          key: AZURE_TENANT_ID
        - objectName: apikey
          key: AZURE_OPENAI_API_KEY
        - objectName: openapiendpoint
          key: AZURE_OPENAI_ENDPOINT
        - objectName: storage
          key: AZURE_STORAGE_CONNECTION_STRING

