sonar.projectKey=Kubernetes-Incident-Manager_dependency-service
sonar.organization=kubernetes-incident-manager
sonar.python.version=3.11
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/*
