apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.global.environment }}
data:
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  POSTGRES_HOST: {{ .Values.postgres.host | quote }}
  REDIS_HOST: {{ .Values.redis.host | quote }}
  API_GATEWAY_URL: "http://api-gateway-svc:8000"
  FRONTEND_API_URL: "/api"
