{{- $namespace := .Values.namespace | default .Release.Namespace -}}
{{- $secrets := .Values.secrets | default dict -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ get $secrets "name" | default "azure-kv-secrets" }}
  namespace: {{ $namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ get $secrets "workloadIdentityClientId" | quote }}
    keyvaultName: {{ get $secrets "keyvaultName" | quote }}
    objects:  |
      array:
        - |
          objectName: postgresuser
          objectType: secret
        - |
          objectName: postgrespassword
          objectType: secret
        - |
          objectName: azuretenantid
          objectType: secret
        - |
          objectName: apikey
          objectType: secret
        - |
          objectName: openapiendpoint
          objectType: secret
        - |
          objectName: storage
          objectType: secret
    tenantId: {{ get $secrets "tenantId" | quote }}
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - objectName: postgresuser
          key: POSTGRES_USER
        - objectName: postgrespassword
          key: POSTGRES_PASSWORD
        - objectName: azuretenantid
          key: AZURE_TENANT_ID
        - objectName: apikey
          key: AZURE_OPENAI_API_KEY
        - objectName: openapiendpoint
          key: AZURE_OPENAI_ENDPOINT
        - objectName: storage
          key: AZURE_STORAGE_CONNECTION_STRING
