apiVersion: v1
kind: ServiceAccount
metadata:
  name: incident-tracker-sa
  namespace: {{ .Values.global.environment }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.global.workloadIdentityClientId | quote }}
  labels:
    azure.workload.identity/use: "true"
