apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: {{ .Values.global.environment }}
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
  namespace: {{ .Values.global.environment }}
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-ui
  namespace: {{ .Values.global.environment }}
spec:
  selector:
    app: frontend-ui
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: incidents-service-svc
  namespace: {{ .Values.global.environment }}
spec:
  selector:
    app: incidents-service
  ports:
    - port: 8004
      targetPort: 8004
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-store-svc
  namespace: {{ .Values.global.environment }}
spec:
  selector:
    app: telemetry-store
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: analysis-service-svc
  namespace: {{ .Values.global.environment }}
spec:
  selector:
    app: analysis-service
  ports:
    - port: 8003
      targetPort: 8003
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: dependency-service-svc
  namespace: {{ .Values.global.environment }}
spec:
  selector:
    app: dependency-service
  ports:
    - port: 8005
      targetPort: 8005
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ingest-service-svc
  namespace: {{ .Values.global.environment }}
spec:
  selector:
    app: ingest-service
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP
