{{- $namespace := .Values.namespace | default .Release.Namespace -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: incident-tracker-sa
  namespace: {{ $namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.secrets.workloadIdentityClientId | quote }}
  labels:
    azure.workload.identity/use: "true"
