variable "resource_group_name" {}
variable "location" {}
variable "vnet_address_space" {}
variable "aks_subnet_prefix" {}
variable "sql_subnet_prefix" {}
variable "pe_subnet_prefix" {}
variable "appgw_subnet_prefix" {}
variable "tags" {}
variable "aks_cluster_name" {}
variable "aks_dns_prefix" {}
variable "aks_service_cidr" {}
variable "aks_dns_service_ip" {}
variable "acr_name" {}
variable "sql_server_name" {}
variable "sql_admin_username" {}
variable "sql_admin_password" {}
variable "kv_name" {}
variable "storage_account_name" {}
variable "vm_admin_username" {}
variable "vm_admin_password" {}
variable "appgw_name" {}
variable "ai_foundry_name" {}