apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: incidenttracker-dev-api-gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Suwetha07/incident-Tracker.git
    targetRevision: main
    path: Final-Capstone/kubernetes/k8s/dev-apps/api-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
