apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: incident-tracker-route
  namespace: dev
spec:
  parentRefs:
    - name: incident-tracker-gateway
  rules:
    # 1. Direct microservice routing (Bypassing Python API Gateway proxy)
    - matches:
        - path:
            type: PathPrefix
            value: /incidents-service
      backendRefs:
        - name: incidents-service-svc
          port: 8004

    - matches:
        - path:
            type: PathPrefix
            value: /telemetry-store
      backendRefs:
        - name: telemetry-store-svc
          port: 8002

    - matches:
        - path:
            type: PathPrefix
            value: /analysis-service
      backendRefs:
        - name: analysis-service-svc
          port: 8003

    - matches:
        - path:
            type: PathPrefix
            value: /dependency-service
      backendRefs:
        - name: dependency-service-svc
          port: 8005

    - matches:
        - path:
            type: PathPrefix
            value: /ingest-service
      backendRefs:
        - name: ingest-service-svc
          port: 8001

    # 2. Cluster Validation Endpoints (Handled by API Gateway)
    - matches:
        - path:
            type: PathPrefix
            value: /cluster
      backendRefs:
        - name: api-gateway-svc
          port: 8000

    # 3. Default route for the Frontend
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: frontend-ui
          port: 80
