apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: incident-tracker-sa
      containers:
        - name: frontend-ui
          image: incidenttracker.azurecr.io/frontend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
