apiVersion: v1
kind: Service
metadata:
  name: incidents-service-svc
  namespace: prod
spec:
  selector:
    app: incidents-service
  ports:
    - port: 8004
      targetPort: 8004
  type: ClusterIP
---
