apiVersion: v1
kind: Service
metadata:
  name: dependency-service-svc
  namespace: dev
spec:
  selector:
    app: dependency-service
  ports:
    - port: 8005
      targetPort: 8005
  type: ClusterIP
---
