apiVersion: v1
kind: ServiceAccount
metadata:
  name: incident-tracker-sa
  namespace: dev
  annotations:
    azure.workload.identity/client-id: "2df9028f-bf9e-438f-9cde-1f1764e4ddfc"
  labels:
    azure.workload.identity/use: "true"
