name: API Gateway CI

on:
  push:
    branches: [develop, main]
    paths:
      - "Final-Capstone/services/api-gateway/**"
  pull_request:
    branches: [develop, main]
    paths:
      - "Final-Capstone/services/api-gateway/**"

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  ci:
    uses: Suwetha07/incident-Tracker/.github/workflows/ci.yaml@main
    with:
      image_name: "api-gateway"
      docker_context: "Final-Capstone/services/api-gateway"
    secrets: inherit
