name: Telemetry Store CI

on:
  push:
    branches: [develop, main]
    paths:
      - "Final-Capstone/services/telemetry-store/**"
  pull_request:
    branches: [develop, main]
    paths:
      - "Final-Capstone/services/telemetry-store/**"

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  ci:
    uses: Suwetha07/incident-Tracker/.github/workflows/ci.yaml@main
    with:
      image_name: "telemetry-store"
      docker_context: "Final-Capstone/services/telemetry-store"
    secrets: inherit
