name: Worker Service CI

on:
  push:
    branches: [develop, main]
    paths:
      - "Final-Capstone/services/worker-service/**"
  pull_request:
    branches: [develop, main]
    paths:
      - "Final-Capstone/services/worker-service/**"

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  ci:
    uses: Suwetha07/incident-Tracker/.github/workflows/ci.yaml@main
    with:
      image_name: "worker-service"
      docker_context: "Final-Capstone/services/worker-service"
    secrets: inherit
