name: Web App CI

on:
  push:
    branches: [develop, main]
    paths:
      - "Final-Capstone/frontend/web-app/**"
  pull_request:
    branches: [develop, main]
    paths:
      - "Final-Capstone/frontend/web-app/**"

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  ci:
    uses: Suwetha07/incident-Tracker/.github/workflows/ci.yaml@main
    with:
      image_name: "web-app"
      docker_context: "Final-Capstone/frontend/web-app"
    secrets: inherit
