name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy-to-aks:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        uses: azure/aks-set-context@v3
        with:
          resource-group: Suwetha-RG
          cluster-name: suwethaaks

      - name: Update Image Tag in Manifests
        run: |
          # Use sed to update the image tag to the new github.sha
          sed -i "s|image: .*/incident-tracker:.*|image: ${{ secrets.ACR_LOGIN_SERVER }}/incident-tracker:${{ github.event.workflow_run.head_sha }}|g" kubernetes/dev/deployments.yaml

      - name: Apply Kubernetes Manifests
        run: kubectl apply -f kubernetes/dev/

      - name: Verify Rollout Status
        run: kubectl rollout status deployment/frontend-ui -n dev

      - name: Run Smoke Tests
        run: |
          echo "Running Smoke Tests..."
          # Insert smoke tests against the AppGateway IP here

      - name: Notification on Success/Failure
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            if ("${{ job.status }}" === "success") {
              console.log("Deployment Successful! ✅");
            } else {
              console.error("Deployment Failed! ❌");
            }
